---
title: "Kemi_Class_Project"
author: "Kemi"
date: "2024-11-12"
output: html_document
---

```{r}
#Summary of final project
Each year, Nigerian journalists publish articles to honor the memory of Dele Giwa, a trailblazing investigative journalist who was tragically killed by a parcel bomb delivered to his Lagos residence in 1986. This study takes a dive into these commemorative articles to identify the dominant themes in news and editorialized articles that commemorated the assassination of Dele Giwa. The study also aims to analyze differences in the commemoration during the military era (1987 to May 1999) and civilian (1999 to 2023).

```

```{r}
#Link to source data on GitHub
https://github.com/kemibus/Kemi_repository/tree/main/dele_giwa
```

```{r}
#install.packages("pdftools")
library(pdftools)
library(tidyverse)
library(pdftools)
library(striprtf)
```


```{r}
# Define the file path for the RTF file
file_path <- "~/GitHub/Kemi_repository/dele_giwa/.rtf"

# Normalize the file path
file_path <- normalizePath(file_path)

# Read and convert RTF to plain text
rtf_text <- read_rtf(file_path)

# Write the plain text to a .txt file
txt_file_path <- gsub("\\.rtf$", ".txt", file_path)
writeLines(rtf_text, txt_file_path)

# Confirm the text file has been created
cat("Text file created at:", txt_file_path)

```